### PR TITLE
Rebasing Chodera lab Master

### PR DESCRIPTION
**Pull request by apayne97**
## Description
Provide a brief description of the data being added here.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by apayne97** [comment]
@hannahbrucemacdonald @jchodera help please, I'm trying to update this fork so that our group can use to make branches and make PRs

**Comment by jchodera** [comment]
Just saw this. Let me take a look.

**Comment by jchodera** [comment]
@apayne97 Do you have stuff in here that hasn't made it into MolSSI yet? Or do you want to start from a clean master in sync with the MolSSI master?

**Comment by apayne97** [comment]
I think some people have stuff in branches that isnt in yet but master
should be good

**Pull request closed without merging**
